# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Temitayo Ogundimu
first_name: Temitayo
middle_name: A.
last_name: Ogundimu
description: >
  Bioinformatics researcher and MSc candidate at Covenant University, specializing in infectious disease genomics, GWAS, and drug resistance.
footer_text: >
  Powered by Jekyll with al-folio theme. Hosted by GitHub Pages.
keywords: bioinformatics, genomics, infectious diseases, gwas, machine learning, data science
lang: en
icon: 🧬 # Using a DNA emoji

url: https://pukkahb.github.io
baseurl: "" # IMPORTANT: This must be blank for your user page.
last_updated: false
impressum_path:
back_to_top: true

# -----------------------------------------------------------------------------
# Social media profiles and contact links
# -----------------------------------------------------------------------------
social:
  - icon: fas fa-envelope
    link: "mailto:your-email@example.com" # Replace with your email address
  - icon: fab fa-github
    link: "https://github.com/pukkahb"
  - icon: ai ai-google-scholar
    link: "#" # Replace with your Google Scholar link
  - icon: fab fa-linkedin
    link: "https://www.linkedin.com/in/oatemitayo/"
  - icon: ai ai-cv
    link: assets/pdf/FiNAL-CV.docx.pdf # Path to your CV

# -----------------------------------------------------------------------------
# Jekyll Scholar (for publications)
# -----------------------------------------------------------------------------
scholar:
  last_name: [Ogundimu]
  first_name: [Temitayo, T., T.A.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending
  max_author_limit: 5
  enable_publication_badges:
    altmetric: true
    dimensions: true
    google_scholar: true
  enable_publication_thumbnails: true

# -----------------------------------------------------------------------------
# Giscus comments
# -----------------------------------------------------------------------------
giscus:
  repo: pukkahb/portfolio-source # your-github-user-name/your-github-repo-name
  repo_id: "" # find this on giscus.app after installing the app
  category: General
  category_id: "" # find this on giscus.app after installing the app
  mapping: pathname
  strict: 0
  reactions_enabled: 1
  input_position: bottom
  theme: preferred_color_scheme
  emit_metadata: 0
  lang: en

# -----------------------------------------------------------------------------
# Optional Features (These are good defaults)
# -----------------------------------------------------------------------------
enable_masonry: true
enable_math: true
enable_darkmode: true
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true

#
#
# --- IGNORE EVERYTHING BELOW THIS LINE ---
# --- (These are advanced settings for the theme to work correctly) ---
#
#

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------
navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true
max_width: 930px

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
keep_files:
  - CNAME
  - .nojekyll
plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false
sass:
  style: compressed
jekyll-minifier:
  compress_javascript: false
  exclude: ["robots.txt", "assets/js/search/*.js"]
terser:
  compress:
    drop_console: true
